apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - servicemonitor.yaml

configMapGenerator:
  - name: projeto-korp-dashboard
    namespace: monitoring

    files:
      - projeto-korp.json=dashboards/projeto-korp.json

generatorOptions:
  disableNameSuffixHash: true

  labels:
    grafana_dashboard: "1"