apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:

  name: http-server-projeto-korp

  namespace: projeto-korp

  labels:
    app: http-server-projeto-korp


spec:

  selector:

    matchLabels:
      app: http-server-projeto-korp


  endpoints:

    - port: http

      path: /metrics

      interval: 15s

      scrapeTimeout: 10s