apiVersion: v1
kind: Service

metadata:
  name: nginx-metrics
  namespace: projeto-korp

spec:
  type: ClusterIP

  selector:
    app: nginx-projeto-korp

  ports:
    - name: metrics
      protocol: TCP
      port: 4040
      targetPort: metrics
