apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: projeto-korp
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/DaviPO2001/desafio_devops_korp.git
    targetRevision: main
    path: kubernetes/manifests

    directory:
      recurse: true

  destination:
    server: https://kubernetes.default.svc
    namespace: projeto-korp

  syncPolicy:
    automated:
      prune: true
      selfHeal: false

    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

  ignoreDifferences:
    - group: apps
      kind: Deployment
      name: http-server-projeto-korp
      namespace: projeto-korp
      jsonPointers:
        - /spec/replicas