Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  config.vm.boot_timeout = 600


  # ========================================================
  # WORKER
  # Sobe primeiro para estar disponivel quando o Ansible
  # for executado a partir do manager.
  # ========================================================

  config.vm.define "worker" do |worker|

    worker.vm.hostname = "projeto-korp-worker"

    worker.vm.network "private_network",
      ip: "192.168.56.21"

    # ------------------------------------------------------
    # PORTAS DE ACESSO PELO WINDOWS/HOST
    # ------------------------------------------------------

    # Argo CD
    worker.vm.network "forwarded_port",
      guest: 30443,
      host: 1000

    # Aplicacao / NGINX
    worker.vm.network "forwarded_port",
      guest: 30080,
      host: 1001

    # Grafana
    worker.vm.network "forwarded_port",
      guest: 30300,
      host: 1002

    # Prometheus
    worker.vm.network "forwarded_port",
      guest: 30900,
      host: 1003


    worker.vm.provider "virtualbox" do |vb|

      vb.memory = "3072"
      vb.cpus = 2

    end

  end


  # ========================================================
  # MANAGER / CONTROL PLANE
  # ========================================================

  config.vm.define "manager" do |manager|

    manager.vm.hostname = "projeto-korp-manager"

    manager.vm.network "private_network",
      ip: "192.168.56.20"

    # Raiz do repositorio
    manager.vm.synced_folder "..", "/projeto-korp"


    # ------------------------------------------------------
    # ANSIBLE
    # ------------------------------------------------------

    manager.vm.provision "shell",
      path: "provision.sh"


    manager.vm.provider "virtualbox" do |vb|

      vb.memory = "4096"
      vb.cpus = 2

    end

  end

end